name: Github Telemetry Scheduled Job

# on:
#   schedule:
#     - cron: "0 0 * * MON"

on: push

env:
  PAT: ${{ secrets.PAT }}

jobs:
  githubTelemetry:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.changesExist.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'v-bpastiu/k8s-adoption-journey'
      
      - name: Setup python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: Install dependecies and run script
        run: |
          ( 
            cd github-telemetry
            pip install -r requirements.txt
            python3 github-telemetry.py
          )

      - name: Check if there are uncommited changes
        run: 'git diff github-telemetry'
        id: changesExist

      - name: Create new branch if there are changes
        if: steps.changesExist.output.changes == true
        run: git checkout -b weekly-telemetry-branch/${{ github.event.repository.updated_at}}

